server {
    listen 80;
    server_name _;

    # Download page
    location /downloads/ {
        alias /usr/share/nginx/html/downloads/;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }

    location / {
        return 301 /downloads/;
    }
}
